baseURL = 'https://tusiqi1.github.io/blog/'
languageCode = 'en-us'
title = 'My New Hugo Project'
theme = 'PaperMod'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 4

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 5

[params]
  math = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  taxonomyCloud = true
  taxonomyCloudTitle = true
